### ISSUE TITLE
Want to join game jam, can't login anywhere

### ISSUE THREAD

**Issue by hwirth** [OneLoneCoder/videos#45]
Sorry for abusing this, but I tried to find a way to contact you to no avail besides this.
YouTube won't let me use the account, I created years ago and new accounts can't be created atm. either.

So, I would like to take part in the game jam.
Is there a way for me to join without a social network account?
https://harald.ist.org/about/contact.html

Btw, contact.html on your web site throws a 404.

Greetings,
H.

**Comment by OneLoneCoder** [comment]
lol, very creative of you XD

The jam is operated on a platform called itch.io. Its not a social media platform, but it collates the submissions and fosters the judging process. Signing up for itch.io does require you create an account, and in their defence its spam free. Their aim is that by hosting jams, some entrants may go on to use itch.io as a publishing platform, at which point they would take a cut. That said, anything you create on the jam and distribute on their platform is 100% yours.

Due to the high number of entrants these days, my hands are a bit tied when it comes to jams, as without the tools they provide it would be too much for me to manage sensibly.

Jx9

**Comment by hwirth** [comment]
Thanks for the quick reply! I now own an account on itch.io :) 
They didn't even force me to verify my @ let alone asking for my phone number.
I am looking forward to coding a new game, curious, what it will be about.
Until then, stay healthy!
